# Generated by Django 3.0.2 on 2020-01-13 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='sub_category',
            field=models.ManyToManyField(blank=True, related_name='_itemcategory_sub_category_+', to='shop.ItemCategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/items/'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/categories/'),
        ),
    ]
