# Generated by Django 3.0.2 on 2020-01-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_address_coupon_order_ordereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_in_stock',
            field=models.IntegerField(default=1),
        ),
    ]
